package com.cms.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

import com.cms.model.enums.AdmissionQuota;
import com.cms.model.enums.EnquiryStatus;
import com.cms.model.enums.Gender;
import com.cms.model.enums.StudentType;

public record EnquiryResponse(
    Long id,
    String name,
    String email,
    String phone,
    Long programId,
    String programName,
    Long courseId,
    String courseName,
    Long academicYearId,
    String academicYearName,
    LocalDate enquiryDate,
    Long referralTypeId,
    String referralTypeName,
    BigDecimal referralCommissionAmount,
    Boolean referralHasCommission,
    EnquiryStatus status,
    Long agentId,
    String agentName,
    String remarks,
    BigDecimal feeDiscussedAmount,
    BigDecimal feeGuidelineTotal,
    BigDecimal referralAdditionalAmount,
    BigDecimal finalCalculatedFee,
    String yearWiseFees,
    String semesterWiseFees,
    StudentType studentType,
    BigDecimal finalizedTotalFee,
    BigDecimal finalizedDiscountAmount,
    String finalizedDiscountReason,
    BigDecimal finalizedNetFee,
    String finalizedBy,
    Instant finalizedAt,
    Long convertedStudentId,
    Long countryId,
    String countryName,
    String state,
    String district,
    Long referredStudentId,
    String referredStudentName,
    Long referredFacultyId,
    String referredFacultyName,
    Long referredStaffId,
    String referredStaffName,
    Instant createdAt,
    Instant updatedAt,
    BigDecimal totalPaidAmount,
    LocalDate dateOfBirth,
    Gender gender,
    AdmissionQuota admissionQuota,
    Long feeStateId,
    String feeStateName,
    String admissionNumber,
    String admissionSource,
    BigDecimal commissionAmount,
    BigDecimal guidelineCommissionAmount
) {}
