export interface Page<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
  first: boolean;
  last: boolean;
}

export type StockIndentStatus = 'DRAFT' | 'SUBMITTED' | 'COMPLETED' | 'CANCELLED';
/** PENDING awaits the department head; APPROVED then awaits the store's own fulfillment decision
 *  (Phase D) — it no longer means "issued". REJECTED is the department head's negative outcome;
 *  DENIED is the store's. FULFILLED covers both store fulfillment paths (direct issue, or a
 *  transfer-in first — see sourceTransferId). PO_RAISED means the store raised a Purchase
 *  Requisition instead. */
export type StockIndentItemStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'FULFILLED' | 'PO_RAISED' | 'DENIED';

export interface StockIndentCreateRequest {
  requestingLocationId: number;
  issuingLocationId: number;
  requestDate?: string;
  notes?: string;
}

export interface StockIndentAddLineRequest {
  productId: number;
  /** Required once the product has any active ProductVariant. */
  variantId?: number;
  requestedQty: number;
  notes?: string;
}

export interface StockIndentResolutionRequest {
  notes?: string;
}

export interface StockIndentReturnLineRequest {
  returnedQty: number;
  notes?: string;
}

export interface StockIndentFulfillViaTransferRequest {
  sourceLocationId: number;
  transferQty: number;
  notes?: string;
}

export interface StockIndentRaisePoRequest {
  qty: number;
  notes?: string;
}

export interface StockIndentFulfillmentContextCandidateLocation {
  locationId: number;
  locationVirtualName: string;
  qtyOnHand: number;
}

export interface StockIndentFulfillmentContext {
  requestedQty: number;
  issuingLocationQtyOnHand: number;
  candidateSourceLocations: StockIndentFulfillmentContextCandidateLocation[];
}

export interface StockIndentItem {
  id: number;
  productId: number;
  productCode: string;
  productName: string;
  variantId: number | null;
  variantCode: string | null;
  variantName: string | null;
  uomCode: string | null;
  requestedQty: number;
  status: StockIndentItemStatus;
  resolvedBy: string | null;
  resolvedAt: string | null;
  resolutionNotes: string | null;
  returnedQty: number;
  notes: string | null;
  storeDecidedBy: string | null;
  storeDecidedAt: string | null;
  storeDecisionNotes: string | null;
  sourceTransferId: number | null;
  raisedRequisitionId: number | null;
  raisedRequisitionItemId: number | null;
}

export interface StockIndent {
  id: number;
  requestingLocationId: number;
  requestingLocationVirtualName: string;
  issuingLocationId: number;
  issuingLocationVirtualName: string;
  status: StockIndentStatus;
  requestDate: string;
  notes: string | null;
  createdBy: string | null;
  createdAt: string;
  submittedBy: string | null;
  submittedAt: string | null;
  completedAt: string | null;
  lineCount: number;
  pendingCount: number;
  isAutoGenerated: boolean;
  lines: StockIndentItem[] | null;
}
