package com.cms.model;

import java.time.Instant;
import java.util.UUID;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.cms.model.enums.ClassScheduleStatus;
import com.cms.model.enums.ClassSessionType;
import com.cms.model.enums.DayOfWeek;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/** Generalizes what was originally a lab-only schedule row (table renamed from lab_schedules
 *  by V293) to cover THEORY, LAB, and CLINICAL sessions. THEORY rows use classroom+period; LAB
 *  rows use lab+period+batch; CLINICAL rows use clinicalVenue+period+batch (CLINICAL added in
 *  V334, previously folded into LAB) — all three session types share the one Period time-slot
 *  master since V331 merged the formerly-separate LabSlot master into it — see the
 *  chk_class_schedule_session_shape CHECK constraint (redefined in V334) for the enforced
 *  shape per sessionType. */
@Entity
@Table(name = "class_schedules")
@EntityListeners(AuditingEntityListener.class)
public class ClassSchedule {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lab_id")
    private Lab lab;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    private Subject subject;

    /** Nullable since R3 Phase 4 (V335): a skeleton row placed before staffing has no faculty yet
     *  — the CHECK constraint enforces it's only ever null while status != PUBLISHED. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "faculty_id")
    private Faculty faculty;

    @Column(name = "batch_name")
    private String batchName;

    /** Real Batch entity backing a LAB row, when the admin picked one from the roster
     *  dropdown instead of typing a free-text label. See V272's additive-then-deprecate note. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "batch_id")
    private Batch batch;

    @Enumerated(EnumType.STRING)
    @Column(name = "day_of_week", nullable = false)
    private DayOfWeek dayOfWeek;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "term_instance_id", nullable = false)
    private TermInstance termInstance;

    @Column(name = "is_active")
    private Boolean isActive;

    @Enumerated(EnumType.STRING)
    @Column(name = "session_type", nullable = false)
    private ClassSessionType sessionType = ClassSessionType.LAB;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private ClassScheduleStatus status = ClassScheduleStatus.PUBLISHED;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id")
    private Classroom classroom;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "period_id")
    private Period period;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "clinical_venue_id")
    private ClinicalVenue clinicalVenue;

    /** Populated for THEORY rows (audience resolution via CourseRegistration) and, going
     *  forward, for LAB rows generated by TimetableGenerationService (which always has it via
     *  Batch.courseOffering) — not retrofitted onto historical rows or required on manual entry. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_offering_id")
    private CourseOffering courseOffering;

    /** Which CohortSection sub-cohort this THEORY session was placed for, once its cohort's
     *  committed Theory room has been split into sections (see V364) -- mirrors
     *  Batch#getCohortSection() for LAB/CLINICAL. Null means "whole cohort": either no committed
     *  CohortRoomAllocation for this cohort/term, or a row placed before V368 added this column.
     *  Never set on LAB/CLINICAL rows; their section scope is derived from their own
     *  Batch#getCohortSection() instead. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cohort_section_id")
    private CohortSection cohortSection;

    /** OC-127 periodSpan: links N consecutive-period rows that together represent one multi-period
     *  session (e.g. a 2-period lab), placed/staffed/removed atomically as one unit. Null for every
     *  ordinary single-period session -- conflict checks stay unchanged, always operating per-row
     *  against each row's own {@link Period}. */
    @Column(name = "session_group_id")
    private UUID sessionGroupId;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public ClassSchedule() {
    }

    /** Legacy LAB-session convenience constructor, kept for existing seed data
     *  (DataLoader/LocalDataSeeder) that predates THEORY support. */
    public ClassSchedule(Lab lab, Subject subject, Faculty faculty, Period period,
                       String batchName, DayOfWeek dayOfWeek, TermInstance termInstance, Boolean isActive) {
        this.lab = lab;
        this.subject = subject;
        this.faculty = faculty;
        this.period = period;
        this.batchName = batchName;
        this.dayOfWeek = dayOfWeek;
        this.termInstance = termInstance;
        this.isActive = isActive;
        this.sessionType = ClassSessionType.LAB;
        this.status = ClassScheduleStatus.PUBLISHED;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Lab getLab() {
        return lab;
    }

    public void setLab(Lab lab) {
        this.lab = lab;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Faculty getFaculty() {
        return faculty;
    }

    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }

    public String getBatchName() {
        return batchName;
    }

    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    public Batch getBatch() {
        return batch;
    }

    public void setBatch(Batch batch) {
        this.batch = batch;
    }

    public DayOfWeek getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(DayOfWeek dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public TermInstance getTermInstance() {
        return termInstance;
    }

    public void setTermInstance(TermInstance termInstance) {
        this.termInstance = termInstance;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public ClassSessionType getSessionType() {
        return sessionType;
    }

    public void setSessionType(ClassSessionType sessionType) {
        this.sessionType = sessionType;
    }

    public ClassScheduleStatus getStatus() {
        return status;
    }

    public void setStatus(ClassScheduleStatus status) {
        this.status = status;
    }

    public Classroom getClassroom() {
        return classroom;
    }

    public void setClassroom(Classroom classroom) {
        this.classroom = classroom;
    }

    public Period getPeriod() {
        return period;
    }

    public void setPeriod(Period period) {
        this.period = period;
    }

    public ClinicalVenue getClinicalVenue() {
        return clinicalVenue;
    }

    public void setClinicalVenue(ClinicalVenue clinicalVenue) {
        this.clinicalVenue = clinicalVenue;
    }

    public CourseOffering getCourseOffering() {
        return courseOffering;
    }

    public void setCourseOffering(CourseOffering courseOffering) {
        this.courseOffering = courseOffering;
    }

    public CohortSection getCohortSection() {
        return cohortSection;
    }

    public void setCohortSection(CohortSection cohortSection) {
        this.cohortSection = cohortSection;
    }

    public UUID getSessionGroupId() {
        return sessionGroupId;
    }

    public void setSessionGroupId(UUID sessionGroupId) {
        this.sessionGroupId = sessionGroupId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
