package com.cms.model;

import java.time.Instant;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.cms.model.enums.ClassScheduleStatus;
import com.cms.model.enums.ClassSessionType;
import com.cms.model.enums.DayOfWeek;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/** Generalizes what was originally a lab-only schedule row (table renamed from lab_schedules
 *  by V293) to cover both THEORY and LAB/CLINICAL sessions. THEORY rows use classroom+period;
 *  LAB rows use lab+labSlot+batch — see the chk_class_schedule_session_shape CHECK constraint
 *  added in V293 for the enforced shape per sessionType. */
@Entity
@Table(name = "class_schedules")
@EntityListeners(AuditingEntityListener.class)
public class ClassSchedule {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lab_id")
    private Lab lab;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    private Subject subject;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "faculty_id", nullable = false)
    private Faculty faculty;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lab_slot_id")
    private LabSlot labSlot;

    @Column(name = "batch_name")
    private String batchName;

    /** Real Batch entity backing a LAB row, when the admin picked one from the roster
     *  dropdown instead of typing a free-text label. See V272's additive-then-deprecate note. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "batch_id")
    private Batch batch;

    @Enumerated(EnumType.STRING)
    @Column(name = "day_of_week", nullable = false)
    private DayOfWeek dayOfWeek;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "term_instance_id", nullable = false)
    private TermInstance termInstance;

    @Column(name = "is_active")
    private Boolean isActive;

    @Enumerated(EnumType.STRING)
    @Column(name = "session_type", nullable = false)
    private ClassSessionType sessionType = ClassSessionType.LAB;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private ClassScheduleStatus status = ClassScheduleStatus.PUBLISHED;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classroom_id")
    private Classroom classroom;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "period_id")
    private Period period;

    /** Populated for THEORY rows (audience resolution via CourseRegistration) and, going
     *  forward, for LAB rows generated by TimetableGenerationService (which always has it via
     *  Batch.courseOffering) — not retrofitted onto historical rows or required on manual entry. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_offering_id")
    private CourseOffering courseOffering;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public ClassSchedule() {
    }

    /** Legacy LAB-session convenience constructor, kept for existing seed data
     *  (DataLoader/LocalDataSeeder) that predates THEORY support. */
    public ClassSchedule(Lab lab, Subject subject, Faculty faculty, LabSlot labSlot,
                       String batchName, DayOfWeek dayOfWeek, TermInstance termInstance, Boolean isActive) {
        this.lab = lab;
        this.subject = subject;
        this.faculty = faculty;
        this.labSlot = labSlot;
        this.batchName = batchName;
        this.dayOfWeek = dayOfWeek;
        this.termInstance = termInstance;
        this.isActive = isActive;
        this.sessionType = ClassSessionType.LAB;
        this.status = ClassScheduleStatus.PUBLISHED;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Lab getLab() {
        return lab;
    }

    public void setLab(Lab lab) {
        this.lab = lab;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Faculty getFaculty() {
        return faculty;
    }

    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }

    public LabSlot getLabSlot() {
        return labSlot;
    }

    public void setLabSlot(LabSlot labSlot) {
        this.labSlot = labSlot;
    }

    public String getBatchName() {
        return batchName;
    }

    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    public Batch getBatch() {
        return batch;
    }

    public void setBatch(Batch batch) {
        this.batch = batch;
    }

    public DayOfWeek getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(DayOfWeek dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public TermInstance getTermInstance() {
        return termInstance;
    }

    public void setTermInstance(TermInstance termInstance) {
        this.termInstance = termInstance;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public ClassSessionType getSessionType() {
        return sessionType;
    }

    public void setSessionType(ClassSessionType sessionType) {
        this.sessionType = sessionType;
    }

    public ClassScheduleStatus getStatus() {
        return status;
    }

    public void setStatus(ClassScheduleStatus status) {
        this.status = status;
    }

    public Classroom getClassroom() {
        return classroom;
    }

    public void setClassroom(Classroom classroom) {
        this.classroom = classroom;
    }

    public Period getPeriod() {
        return period;
    }

    public void setPeriod(Period period) {
        this.period = period;
    }

    public CourseOffering getCourseOffering() {
        return courseOffering;
    }

    public void setCourseOffering(CourseOffering courseOffering) {
        this.courseOffering = courseOffering;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
