CREATE TABLE students (
    id                 BIGSERIAL PRIMARY KEY,
    roll_number        VARCHAR(255)                NOT NULL UNIQUE,
    first_name         VARCHAR(255)                NOT NULL,
    last_name          VARCHAR(255)                NOT NULL,
    email              VARCHAR(255)                NOT NULL UNIQUE,
    phone              VARCHAR(255),
    program_id         BIGINT                      NOT NULL REFERENCES programs(id),
    semester           INTEGER                     NOT NULL,
    admission_date     DATE                        NOT NULL,
    lab_batch          VARCHAR(255),
    status             VARCHAR(255)                NOT NULL,
    date_of_birth      DATE,
    gender             VARCHAR(255),
    aadhar_number      VARCHAR(255),
    nationality        VARCHAR(255),
    religion           VARCHAR(255),
    community_category VARCHAR(255),
    caste              VARCHAR(255),
    blood_group        VARCHAR(255),
    father_name        VARCHAR(255),
    mother_name        VARCHAR(255),
    parent_mobile      VARCHAR(255),
    postal_address     VARCHAR(255),
    street             VARCHAR(255),
    city               VARCHAR(255),
    district           VARCHAR(255),
    state              VARCHAR(255),
    pincode            VARCHAR(255),
    created_at         TIMESTAMP WITH TIME ZONE    NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE    NOT NULL
);
