-- V224: Unified outbound payment queue for OneBook integration.
--
-- Every payment (commission, refund, scholarship) transmitted to OneBook
-- gets a row here. The reference_id is generated by OneCMS and sent with
-- every outbound call so OneBook can call back with that ID to update status.

CREATE TABLE onebook_payment_requests (
    id                    BIGSERIAL PRIMARY KEY,
    reference_id          VARCHAR(60) NOT NULL UNIQUE,
    payment_type          VARCHAR(30) NOT NULL,   -- COMMISSION | REFUND | SCHOLARSHIP
    entity_id             BIGINT NOT NULL,
    entity_table          VARCHAR(100),           -- source table name for audit
    recipient_name        VARCHAR(255),
    recipient_account     VARCHAR(255),
    recipient_ifsc        VARCHAR(20),
    recipient_bank_name   VARCHAR(150),
    amount                NUMERIC(12, 2) NOT NULL,
    status                VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    error_message         TEXT,
    transmitted_at        TIMESTAMP WITH TIME ZONE,
    onebook_txn_id        VARCHAR(255),
    onebook_status        VARCHAR(50),
    onebook_paid_date     DATE,
    onebook_payment_mode  VARCHAR(50),
    onebook_remarks       TEXT,
    onebook_raw_response  JSONB,
    approved_by           VARCHAR(255),
    approved_at           TIMESTAMP WITH TIME ZONE,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_obpr_entity      ON onebook_payment_requests(entity_id, payment_type);
CREATE INDEX idx_obpr_status      ON onebook_payment_requests(status);
CREATE INDEX idx_obpr_reference   ON onebook_payment_requests(reference_id);
