-- Phase C of the Stock Indent auto-indent feature (see docs/inventory-management/DECISION_LOG.md's
-- 2026-09-21 "OC-206 reopened" entry) — marks a Stock Indent as auto-generated by the reorder
-- detection job (AutoIndentService) vs. manually raised by a person, per the user's own confirmed
-- decision that both share one entity/lifecycle. Header-level flag: an auto-generated indent's
-- lines all come from the same detection run, so there's nothing to track per-line. Column name
-- verified against V446/V531 (stock_indents).

ALTER TABLE stock_indents ADD COLUMN is_auto_generated BOOLEAN NOT NULL DEFAULT FALSE;
