package com.cms.inventory.indent.service;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cms.inventory.catalog.model.Product;
import com.cms.inventory.catalog.repository.ProductRepository;
import com.cms.inventory.catalog.repository.ProductVariantRepository;
import com.cms.inventory.indent.dto.StockIndentAddLineRequest;
import com.cms.inventory.indent.dto.StockIndentResponse;
import com.cms.inventory.indent.model.IndentOpenQtyProjection;
import com.cms.inventory.indent.repository.StockIndentItemRepository;
import com.cms.inventory.stock.model.ReorderConfigShortageProjection;
import com.cms.inventory.stock.repository.ProductLocationReorderConfigRepository;

/**
 * Phase C of the Stock Indent auto-indent feature (see the "OC-206 reopened" decision-log entry,
 * 2026-09-21) — a scheduled job (plus an on-demand "Run Now" trigger) that reads {@code
 * ProductLocationReorderConfig} rows, nets each one against current stock <em>and</em> whatever's
 * already open on a Stock Indent, and auto-generates one {@link StockIndentService#createAutoGenerated}
 * header per (requesting location, default supplying store) pair — bundling every product needing
 * restock from the same store into a single header, the same way a person would build one manual
 * request rather than a flurry of single-product ones. Mirrors {@code WantedListService}'s own
 * shape almost exactly (same MRP netting formula, same hybrid lot-sizing rule), the closest
 * in-repo precedent — see that class's own docs for the general approach.
 */
@Service
@Transactional(readOnly = true)
public class AutoIndentService {

    private final ProductLocationReorderConfigRepository configRepository;
    private final StockIndentItemRepository indentItemRepository;
    private final ProductRepository productRepository;
    private final ProductVariantRepository variantRepository;
    private final StockIndentService stockIndentService;

    public AutoIndentService(ProductLocationReorderConfigRepository configRepository,
                              StockIndentItemRepository indentItemRepository,
                              ProductRepository productRepository,
                              ProductVariantRepository variantRepository,
                              StockIndentService stockIndentService) {
        this.configRepository = configRepository;
        this.indentItemRepository = indentItemRepository;
        this.productRepository = productRepository;
        this.variantRepository = variantRepository;
        this.stockIndentService = stockIndentService;
    }

    /** Nightly shortage-netting run — offset 30 minutes after the Wanted List's own 5:00 run so
     *  the two scheduled jobs never contend for the same tables at once. */
    @Scheduled(cron = "0 30 5 * * *")
    @Transactional
    public void scheduledGenerate() {
        generate();
    }

    /**
     * Runs the same netting computation on demand (the "Run Now" action). Returns how many new
     * Stock Indent lines were created (not headers — several lines can share one auto-generated
     * header when they target the same store).
     */
    @Transactional
    public int generate() {
        List<ReorderConfigShortageProjection> candidates = configRepository.findShortageCandidates();
        if (candidates.isEmpty()) return 0;

        Map<String, BigDecimal> openQtyByKey = indentItemRepository.findOpenQtyByProductAndRequestingLocation().stream()
            .collect(Collectors.toMap(p -> key(p.getProductId(), p.getLocationId()), IndentOpenQtyProjection::getQty));

        Map<Long, Product> products = productRepository
            .findAllById(candidates.stream().map(ReorderConfigShortageProjection::getProductId).distinct().toList())
            .stream().collect(Collectors.toMap(Product::getId, p -> p));

        Map<GroupKey, List<Candidate>> grouped = new LinkedHashMap<>();
        for (ReorderConfigShortageProjection candidate : candidates) {
            // A config's own save-time gate requires a supplying store before auto-indent can be
            // enabled, but the location's store can still be unset afterward (see the Phase B
            // decision-log entry) — skip rather than fail the whole run over one drifted config.
            if (candidate.getDefaultSupplyingLocationId() == null) continue;

            Product product = products.get(candidate.getProductId());
            if (product == null || !Boolean.TRUE.equals(product.getIsActive())) continue;

            // Reorder policy is product-level only (same simplification as Product.reorderLevel/
            // reorderQty for the Wanted List) — a product with active variants has no way to guess
            // which one needs restocking, so it's skipped rather than guessed at.
            if (variantRepository.existsByProductIdAndIsActiveTrue(candidate.getProductId())) continue;

            String key = key(candidate.getProductId(), candidate.getLocationId());
            BigDecimal openQty = openQtyByKey.getOrDefault(key, BigDecimal.ZERO);
            BigDecimal netRequirement = candidate.getReorderLevel().subtract(candidate.getQtyOnHand().add(openQty));
            if (netRequirement.compareTo(BigDecimal.ZERO) <= 0) continue;

            BigDecimal lotSize = candidate.getReorderQty() != null ? candidate.getReorderQty() : netRequirement;
            BigDecimal suggestedQty = lotSize.max(netRequirement);
            if (candidate.getMaxStockQty() != null) {
                BigDecimal cap = candidate.getMaxStockQty().subtract(candidate.getQtyOnHand());
                if (cap.signum() > 0) suggestedQty = suggestedQty.min(cap);
            }

            GroupKey groupKey = new GroupKey(candidate.getLocationId(), candidate.getDefaultSupplyingLocationId());
            grouped.computeIfAbsent(groupKey, k -> new ArrayList<>()).add(new Candidate(candidate, product, suggestedQty));
        }

        int created = 0;
        for (Map.Entry<GroupKey, List<Candidate>> entry : grouped.entrySet()) {
            GroupKey groupKey = entry.getKey();
            List<Candidate> lines = entry.getValue();

            StockIndentResponse header = stockIndentService.createAutoGenerated(
                groupKey.requestingLocationId(), groupKey.issuingLocationId(), LocalDate.now(),
                "Auto-generated by Reorder Configuration");

            for (Candidate line : lines) {
                stockIndentService.addLine(header.id(), new StockIndentAddLineRequest(
                    line.product().getId(), null, line.suggestedQty(),
                    "Reorder level " + line.projection().getReorderLevel() + ", on hand " + line.projection().getQtyOnHand()));
            }
            stockIndentService.submit(header.id(), "auto-indent");
            created += lines.size();
        }
        return created;
    }

    private static String key(Long productId, Long locationId) {
        return productId + "-" + locationId;
    }

    private record GroupKey(Long requestingLocationId, Long issuingLocationId) {}

    private record Candidate(ReorderConfigShortageProjection projection, Product product, BigDecimal suggestedQty) {}
}
