package com.cms.inventory.indent.service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.cms.exception.ResourceNotFoundException;
import com.cms.inventory.catalog.model.Product;
import com.cms.inventory.catalog.model.ProductVariant;
import com.cms.inventory.catalog.repository.ProductRepository;
import com.cms.inventory.catalog.repository.ProductVariantRepository;
import com.cms.inventory.indent.dto.StockIndentAddLineRequest;
import com.cms.inventory.indent.dto.StockIndentCreateRequest;
import com.cms.inventory.indent.dto.StockIndentFulfillViaTransferRequest;
import com.cms.inventory.indent.dto.StockIndentFulfillmentContextResponse;
import com.cms.inventory.indent.dto.StockIndentItemResponse;
import com.cms.inventory.indent.dto.StockIndentRaisePoRequest;
import com.cms.inventory.indent.dto.StockIndentResolutionRequest;
import com.cms.inventory.indent.dto.StockIndentResponse;
import com.cms.inventory.indent.dto.StockIndentReturnLineRequest;
import com.cms.inventory.indent.model.StockIndent;
import com.cms.inventory.indent.model.StockIndentItem;
import com.cms.inventory.indent.model.enums.StockIndentItemStatus;
import com.cms.inventory.indent.model.enums.StockIndentStatus;
import com.cms.inventory.indent.repository.StockIndentItemRepository;
import com.cms.inventory.indent.repository.StockIndentRepository;
import com.cms.inventory.procurement.dto.PurchaseRequisitionAddLineRequest;
import com.cms.inventory.procurement.dto.PurchaseRequisitionCreateRequest;
import com.cms.inventory.procurement.dto.PurchaseRequisitionItemResponse;
import com.cms.inventory.procurement.model.PurchaseRequisition;
import com.cms.inventory.procurement.model.PurchaseRequisitionItem;
import com.cms.inventory.procurement.repository.PurchaseRequisitionItemRepository;
import com.cms.inventory.procurement.repository.PurchaseRequisitionRepository;
import com.cms.inventory.procurement.service.PurchaseRequisitionService;
import com.cms.inventory.stock.dto.StockMovementRequest;
import com.cms.inventory.stock.dto.StockTransferAddLineRequest;
import com.cms.inventory.stock.dto.StockTransferCreateRequest;
import com.cms.inventory.stock.model.InventoryLocation;
import com.cms.inventory.stock.model.StockTransfer;
import com.cms.inventory.stock.model.enums.LocationRole;
import com.cms.inventory.stock.repository.InventoryLocationRepository;
import com.cms.inventory.stock.repository.LocationQtyProjection;
import com.cms.inventory.stock.repository.StockBalanceRepository;
import com.cms.inventory.stock.repository.StockTransferRepository;
import com.cms.inventory.stock.service.StockMovementService;
import com.cms.inventory.stock.service.StockTransferService;

/**
 * Owns the Stock Indent workflow — Phase 4's ("Requests, Issues & Returns") first slice, extended
 * in Phase D (2026-09-21, see the "OC-206 reopened" decision-log entries) into a two-decision-point
 * lifecycle: {@link #approveLine}/{@link #rejectLine} are the department head's own sign-off
 * (PENDING -> APPROVED/REJECTED, no stock movement any more), then {@link #fulfillLine}/{@link
 * #fulfillViaTransferLine}/{@link #raisePoLine}/{@link #denyLine} are the store's own fulfillment
 * decision on an {@code APPROVED} line (-> FULFILLED/PO_RAISED/DENIED). Both manual and
 * auto-generated ({@code isAutoGenerated}) indents share this one lifecycle — a deliberate,
 * user-confirmed decision not to build a second parallel document type.
 */
@Service
@Transactional(readOnly = true)
public class StockIndentService {

    private final StockIndentRepository requestRepository;
    private final StockIndentItemRepository lineRepository;
    private final InventoryLocationRepository locationRepository;
    private final ProductRepository productRepository;
    private final StockMovementService stockMovementService;
    private final ProductVariantRepository variantRepository;
    private final StockBalanceRepository balanceRepository;
    private final StockTransferService stockTransferService;
    private final StockTransferRepository stockTransferRepository;
    private final PurchaseRequisitionService purchaseRequisitionService;
    private final PurchaseRequisitionRepository purchaseRequisitionRepository;
    private final PurchaseRequisitionItemRepository purchaseRequisitionItemRepository;

    public StockIndentService(StockIndentRepository requestRepository,
                               StockIndentItemRepository lineRepository,
                               InventoryLocationRepository locationRepository,
                               ProductRepository productRepository,
                               StockMovementService stockMovementService,
                               ProductVariantRepository variantRepository,
                               StockBalanceRepository balanceRepository,
                               StockTransferService stockTransferService,
                               StockTransferRepository stockTransferRepository,
                               PurchaseRequisitionService purchaseRequisitionService,
                               PurchaseRequisitionRepository purchaseRequisitionRepository,
                               PurchaseRequisitionItemRepository purchaseRequisitionItemRepository) {
        this.requestRepository = requestRepository;
        this.lineRepository = lineRepository;
        this.locationRepository = locationRepository;
        this.productRepository = productRepository;
        this.stockMovementService = stockMovementService;
        this.variantRepository = variantRepository;
        this.balanceRepository = balanceRepository;
        this.stockTransferService = stockTransferService;
        this.stockTransferRepository = stockTransferRepository;
        this.purchaseRequisitionService = purchaseRequisitionService;
        this.purchaseRequisitionRepository = purchaseRequisitionRepository;
        this.purchaseRequisitionItemRepository = purchaseRequisitionItemRepository;
    }

    @Transactional
    public StockIndentResponse create(StockIndentCreateRequest request, String createdBy) {
        StockIndent indent = createDraft(request.requestingLocationId(), request.issuingLocationId(),
            request.requestDate(), request.notes(), createdBy, false);
        return toResponse(requestRepository.save(indent));
    }

    /**
     * Same DRAFT-header creation as {@link #create}, flagged {@code isAutoGenerated} — for {@code
     * AutoIndentService} only, never exposed on the public {@link StockIndentCreateRequest} DTO so
     * an ordinary API caller can't mark their own request auto-generated. The caller still adds
     * lines and submits through this service's normal {@link #addLine}/{@link #submit}, exactly
     * like a manually-built indent — see the "OC-206 reopened" decision-log entry for why both
     * share one lifecycle.
     */
    @Transactional
    public StockIndentResponse createAutoGenerated(Long requestingLocationId, Long issuingLocationId, LocalDate requestDate, String notes) {
        StockIndent indent = createDraft(requestingLocationId, issuingLocationId, requestDate, notes, "auto-indent", true);
        return toResponse(requestRepository.save(indent));
    }

    private StockIndent createDraft(Long requestingLocationId, Long issuingLocationId, LocalDate requestDate,
                                     String notes, String createdBy, boolean autoGenerated) {
        if (requestingLocationId.equals(issuingLocationId)) {
            throw new IllegalArgumentException("Requesting and issuing locations must be different");
        }
        InventoryLocation requestingLocation = locationRepository.findById(requestingLocationId)
            .orElseThrow(() -> new ResourceNotFoundException("Inventory location not found with id: " + requestingLocationId));
        InventoryLocation issuingLocation = locationRepository.findById(issuingLocationId)
            .orElseThrow(() -> new ResourceNotFoundException("Inventory location not found with id: " + issuingLocationId));
        requireCanRequest(requestingLocation);
        requireCanIssue(issuingLocation);

        StockIndent indent = new StockIndent();
        indent.setRequestingLocation(requestingLocation);
        indent.setIssuingLocation(issuingLocation);
        indent.setStatus(StockIndentStatus.DRAFT);
        indent.setRequestDate(requestDate != null ? requestDate : LocalDate.now());
        indent.setNotes(trim(notes));
        indent.setCreatedBy(createdBy);
        indent.setCreatedAt(Instant.now());
        indent.setUpdatedAt(Instant.now());
        indent.setIsAutoGenerated(autoGenerated);
        return indent;
    }

    public Page<StockIndentResponse> findPage(Long locationId, String status, Pageable pageable) {
        Specification<StockIndent> spec = (root, query, cb) -> {
            var predicate = cb.conjunction();
            if (locationId != null) {
                predicate = cb.and(predicate, cb.or(
                    cb.equal(root.get("requestingLocation").get("id"), locationId),
                    cb.equal(root.get("issuingLocation").get("id"), locationId)));
            }
            if (status != null && !status.isBlank()) predicate = cb.and(predicate, cb.equal(root.get("status"), parseStatus(status)));
            return predicate;
        };
        return requestRepository.findAll(spec, pageable).map(r -> toResponse(r, false));
    }

    public StockIndentResponse findById(Long id) {
        return toResponse(requireRequest(id));
    }

    @Transactional
    public StockIndentItemResponse addLine(Long requestId, StockIndentAddLineRequest request) {
        StockIndent indent = requireRequest(requestId);
        requireStatus(indent, StockIndentStatus.DRAFT, "add a product to");
        Product product = productRepository.findById(request.productId())
            .orElseThrow(() -> new ResourceNotFoundException("Product not found with id: " + request.productId()));
        ProductVariant variant = resolveVariant(product, request.variantId());
        boolean alreadyOnRequest = variant != null
            ? lineRepository.existsByStockIndentIdAndProductIdAndVariantId(requestId, product.getId(), variant.getId())
            : lineRepository.existsByStockIndentIdAndProductIdAndVariantIsNull(requestId, product.getId());
        if (alreadyOnRequest) {
            throw new IllegalArgumentException("This product is already on the request");
        }

        StockIndentItem line = new StockIndentItem();
        line.setStockIndent(indent);
        line.setProduct(product);
        line.setVariant(variant);
        line.setRequestedQty(request.requestedQty());
        line.setNotes(trim(request.notes()));
        return toLineResponse(lineRepository.save(line));
    }

    @Transactional
    public void removeLine(Long requestId, Long lineId) {
        StockIndent indent = requireRequest(requestId);
        requireStatus(indent, StockIndentStatus.DRAFT, "remove a line from");
        StockIndentItem line = requireLine(indent, lineId);
        lineRepository.delete(line);
    }

    @Transactional
    public StockIndentResponse submit(Long requestId, String submittedBy) {
        StockIndent indent = requireRequest(requestId);
        requireStatus(indent, StockIndentStatus.DRAFT, "submit");
        List<StockIndentItem> lines = lineRepository.findByStockIndentIdOrderByIdAsc(requestId);
        if (lines.isEmpty()) {
            throw new IllegalArgumentException("Add at least one product to the request before submitting");
        }
        indent.setStatus(StockIndentStatus.SUBMITTED);
        indent.setSubmittedBy(submittedBy);
        indent.setSubmittedAt(Instant.now());
        indent.setUpdatedAt(Instant.now());
        requestRepository.save(indent);
        return toResponse(indent);
    }

    /**
     * The department head's own sign-off — Phase D split this from fulfillment entirely. No stock
     * moves here any more; an approved line is routed to the store's own fulfillment decision
     * ({@link #fulfillLine}/{@link #fulfillViaTransferLine}/{@link #raisePoLine}/{@link
     * #denyLine}), not issued immediately.
     */
    @Transactional
    public StockIndentItemResponse approveLine(Long requestId, Long lineId, StockIndentResolutionRequest request, String resolvedBy) {
        StockIndent indent = requireRequest(requestId);
        requireStatus(indent, StockIndentStatus.SUBMITTED, "approve a line on");
        StockIndentItem line = requireLine(indent, lineId);
        if (line.getStatus() != StockIndentItemStatus.PENDING) {
            throw new IllegalArgumentException("This line has already been resolved");
        }

        line.setStatus(StockIndentItemStatus.APPROVED);
        line.setResolvedBy(resolvedBy);
        line.setResolvedAt(Instant.now());
        line.setResolutionNotes(trim(request != null ? request.notes() : null));
        lineRepository.save(line);
        return toLineResponse(line);
    }

    @Transactional
    public StockIndentItemResponse rejectLine(Long requestId, Long lineId, StockIndentResolutionRequest request, String resolvedBy) {
        StockIndent indent = requireRequest(requestId);
        requireStatus(indent, StockIndentStatus.SUBMITTED, "reject a line on");
        StockIndentItem line = requireLine(indent, lineId);
        if (line.getStatus() != StockIndentItemStatus.PENDING) {
            throw new IllegalArgumentException("This line has already been resolved");
        }
        line.setStatus(StockIndentItemStatus.REJECTED);
        line.setResolvedBy(resolvedBy);
        line.setResolvedAt(Instant.now());
        line.setResolutionNotes(trim(request != null ? request.notes() : null));
        lineRepository.save(line);
        completeIfResolved(indent);
        return toLineResponse(line);
    }

    /**
     * The context a store needs to decide how to fulfill an {@code APPROVED} line — its own
     * current stock, and every other location currently holding any of the same product, sorted
     * by quantity descending so the biggest surplus sorts first. See {@link
     * StockIndentFulfillmentContextResponse}.
     */
    public StockIndentFulfillmentContextResponse getFulfillmentContext(Long requestId, Long lineId) {
        StockIndent indent = requireRequest(requestId);
        StockIndentItem line = requireLine(indent, lineId);
        Long productId = line.getProduct().getId();
        Long issuingLocationId = indent.getIssuingLocation().getId();
        Long requestingLocationId = indent.getRequestingLocation().getId();

        Map<Long, BigDecimal> qtyByLocation = balanceRepository.sumQtyByLocationForProduct(productId).stream()
            .collect(Collectors.toMap(LocationQtyProjection::getLocationId, LocationQtyProjection::getQty));

        BigDecimal issuingQty = qtyByLocation.getOrDefault(issuingLocationId, BigDecimal.ZERO);

        List<Long> otherLocationIds = qtyByLocation.entrySet().stream()
            .filter(e -> !e.getKey().equals(issuingLocationId) && !e.getKey().equals(requestingLocationId))
            .filter(e -> e.getValue().signum() > 0)
            .sorted(Map.Entry.<Long, BigDecimal>comparingByValue().reversed())
            .map(Map.Entry::getKey)
            .toList();
        Map<Long, InventoryLocation> otherLocations = locationRepository.findAllById(otherLocationIds).stream()
            .collect(Collectors.toMap(InventoryLocation::getId, l -> l));

        List<StockIndentFulfillmentContextResponse.CandidateSourceLocation> candidates = otherLocationIds.stream()
            .map(id -> otherLocations.get(id))
            .filter(l -> l != null && Boolean.TRUE.equals(l.getIsActive()))
            .map(l -> new StockIndentFulfillmentContextResponse.CandidateSourceLocation(l.getId(), l.getVirtualName(), qtyByLocation.get(l.getId())))
            .toList();

        return new StockIndentFulfillmentContextResponse(line.getRequestedQty(), issuingQty, candidates);
    }

    /** The store fulfills directly from its own on-hand stock — the same {@code ISSUE} movement
     *  the pre-Phase-D {@code approveLine} used to post immediately on approval. */
    @Transactional
    public StockIndentItemResponse fulfillLine(Long requestId, Long lineId, StockIndentResolutionRequest request, String actor) {
        StockIndent indent = requireRequest(requestId);
        StockIndentItem line = requireApprovedLine(indent, lineId);

        stockMovementService.recordMovement(new StockMovementRequest(
            line.getProduct().getId(), line.getVariant() != null ? line.getVariant().getId() : null,
            indent.getIssuingLocation().getId(), null, null,
            "ISSUE", null, line.getRequestedQty(), null,
            "Stock Indent #" + indent.getId() + " to " + indent.getRequestingLocation().getVirtualName(), null
        ), actor);

        markStoreDecided(line, StockIndentItemStatus.FULFILLED, actor, request != null ? request.notes() : null);
        completeIfResolved(indent);
        return toLineResponse(line);
    }

    /**
     * The store doesn't have enough itself, but another location does — pulls the shortfall in
     * via a real {@link StockTransferService} transfer (source -> the issuing location) first,
     * then issues to the requester exactly like {@link #fulfillLine}. Two postings, not one direct
     * transfer to the requester (decision #5 of the "OC-206 reopened" entry): the store's own
     * stock ledger should always reflect everything it actually dispatches.
     */
    @Transactional
    public StockIndentItemResponse fulfillViaTransferLine(Long requestId, Long lineId, StockIndentFulfillViaTransferRequest request, String actor) {
        StockIndent indent = requireRequest(requestId);
        StockIndentItem line = requireApprovedLine(indent, lineId);
        if (request.sourceLocationId().equals(indent.getIssuingLocation().getId())) {
            throw new IllegalArgumentException("Source location must be different from the issuing location");
        }

        var transferResponse = stockTransferService.create(
            new StockTransferCreateRequest(request.sourceLocationId(), indent.getIssuingLocation().getId(), LocalDate.now(),
                "Stock Indent #" + indent.getId() + " line #" + line.getId() + " shortfall cover"), actor);
        stockTransferService.addLine(transferResponse.id(), new StockTransferAddLineRequest(
            line.getProduct().getId(), line.getVariant() != null ? line.getVariant().getId() : null,
            request.transferQty(), null, null, null));
        stockTransferService.complete(transferResponse.id(), actor);

        stockMovementService.recordMovement(new StockMovementRequest(
            line.getProduct().getId(), line.getVariant() != null ? line.getVariant().getId() : null,
            indent.getIssuingLocation().getId(), null, null,
            "ISSUE", null, line.getRequestedQty(), null,
            "Stock Indent #" + indent.getId() + " to " + indent.getRequestingLocation().getVirtualName()
                + " (covered via Stock Transfer #" + transferResponse.id() + ")", null
        ), actor);

        line.setSourceTransfer(stockTransferRepository.getReferenceById(transferResponse.id()));
        markStoreDecided(line, StockIndentItemStatus.FULFILLED, actor, request.notes());
        completeIfResolved(indent);
        return toLineResponse(line);
    }

    /**
     * No stock anywhere covers the shortfall — raises a real Purchase Requisition against the
     * issuing (store) location instead, submitted immediately (mirrors {@code
     * WantedListService.convert}'s own "create, add the line, submit in one go" shape). Terminal:
     * the eventual restock is a separate, disconnected event once that requisition's PO/GRN cycle
     * completes — this indent line's job ends here, see the "OC-206 reopened" decision-log entry.
     * Raised at the base product only — {@code PurchaseRequisition} has no variant-level lines
     * (same product-level scoping the reorder config itself already accepts).
     */
    @Transactional
    public StockIndentItemResponse raisePoLine(Long requestId, Long lineId, StockIndentRaisePoRequest request, String actor) {
        StockIndent indent = requireRequest(requestId);
        StockIndentItem line = requireApprovedLine(indent, lineId);

        var requisition = purchaseRequisitionService.create(
            new PurchaseRequisitionCreateRequest(indent.getIssuingLocation().getId(), LocalDate.now(),
                "From Stock Indent #" + indent.getId() + " line #" + line.getId()), actor);
        PurchaseRequisitionItemResponse requisitionLine = purchaseRequisitionService.addLine(requisition.id(),
            new PurchaseRequisitionAddLineRequest(line.getProduct().getId(), request.qty(),
                line.getVariant() != null ? "For variant: " + line.getVariant().getVariantName() : null));
        purchaseRequisitionService.submit(requisition.id(), actor);

        line.setRaisedRequisition(purchaseRequisitionRepository.getReferenceById(requisition.id()));
        line.setRaisedRequisitionItem(purchaseRequisitionItemRepository.getReferenceById(requisitionLine.id()));
        markStoreDecided(line, StockIndentItemStatus.PO_RAISED, actor, request.notes());
        completeIfResolved(indent);
        return toLineResponse(line);
    }

    /** The store declines to fulfill — distinct from the department head's own {@link #rejectLine}. */
    @Transactional
    public StockIndentItemResponse denyLine(Long requestId, Long lineId, StockIndentResolutionRequest request, String actor) {
        StockIndent indent = requireRequest(requestId);
        StockIndentItem line = requireApprovedLine(indent, lineId);
        markStoreDecided(line, StockIndentItemStatus.DENIED, actor, request != null ? request.notes() : null);
        completeIfResolved(indent);
        return toLineResponse(line);
    }

    private StockIndentItem requireApprovedLine(StockIndent indent, Long lineId) {
        requireStatus(indent, StockIndentStatus.SUBMITTED, "act on a line on");
        StockIndentItem line = requireLine(indent, lineId);
        if (line.getStatus() != StockIndentItemStatus.APPROVED) {
            throw new IllegalArgumentException(
                "This line is " + line.getStatus().name().toLowerCase(Locale.ROOT) + " — it must be approved by the department head first");
        }
        return line;
    }

    private void markStoreDecided(StockIndentItem line, StockIndentItemStatus status, String actor, String notes) {
        line.setStatus(status);
        line.setStoreDecidedBy(actor);
        line.setStoreDecidedAt(Instant.now());
        line.setStoreDecisionNotes(trim(notes));
        lineRepository.save(line);
    }

    @Transactional
    public void cancel(Long requestId) {
        StockIndent indent = requireRequest(requestId);
        requireStatus(indent, StockIndentStatus.DRAFT, "cancel");
        indent.setStatus(StockIndentStatus.CANCELLED);
        indent.setUpdatedAt(Instant.now());
        requestRepository.save(indent);
    }

    private void completeIfResolved(StockIndent indent) {
        if (indent.getStatus() != StockIndentStatus.SUBMITTED) return;
        boolean anyUnresolved = lineRepository.existsByStockIndentIdAndStatusIn(indent.getId(),
            List.of(StockIndentItemStatus.PENDING, StockIndentItemStatus.APPROVED));
        if (!anyUnresolved) {
            indent.setStatus(StockIndentStatus.COMPLETED);
            indent.setCompletedAt(Instant.now());
            indent.setUpdatedAt(Instant.now());
            requestRepository.save(indent);
        }
    }

    /** Same weighted-average formula {@code StockMovementService}'s own decrease-valuation uses,
     *  and the same lookup {@code StockTransferService.currentUnbatchedUnitCost} uses — without
     *  it, an Internal Return's INCREASE movement would resolve to a null unit cost, which {@code
     *  StockMovementService.recordMovement} defaults to zero on an increase, silently diluting the
     *  issuing location's weighted-average cost on every return. */
    private BigDecimal currentUnbatchedUnitCost(Long productId, Long variantId, Long locationId) {
        var balance = variantId != null
            ? balanceRepository.findByProductIdAndVariantIdAndLocationIdAndBatchIsNull(productId, variantId, locationId)
            : balanceRepository.findByProductIdAndVariantIsNullAndLocationIdAndBatchIsNull(productId, locationId);
        return balance
            .filter(b -> b.getQtyOnHand().signum() > 0)
            .map(b -> b.getValueOnHand().divide(b.getQtyOnHand(), 2, RoundingMode.HALF_UP))
            .orElse(BigDecimal.ZERO);
    }

    /**
     * Resolves {@code variantId} against {@code product}, enforcing that it actually belongs to
     * that product and that one is given at all once the product has any active variant — the
     * same "variant becomes required once the product has any" rule as {@code
     * StockMovementService.resolveVariant}.
     */
    private ProductVariant resolveVariant(Product product, Long variantId) {
        if (variantId != null) {
            return variantRepository.findByIdAndProductId(variantId, product.getId())
                .orElseThrow(() -> new IllegalArgumentException(
                    "Variant " + variantId + " does not belong to '" + product.getProductName() + "'"));
        }
        if (variantRepository.existsByProductIdAndIsActiveTrue(product.getId())) {
            throw new IllegalArgumentException(
                "'" + product.getProductName() + "' has active variants — select one for this line");
        }
        return null;
    }

    /** A {@code STORE}-role location is the parent — it stocks and issues, never requests. */
    private void requireCanRequest(InventoryLocation location) {
        if (location.getLocationRole() == LocationRole.STORE) {
            throw new IllegalArgumentException(
                "'" + location.getVirtualName() + "' is a store location and cannot request stock — pick a requesting-point location instead");
        }
    }

    /** A {@code REQUESTING_POINT}-role location is a sister — it draws stock, never issues it
     *  to another location, so sisters can never request-from-issue directly between each other. */
    private void requireCanIssue(InventoryLocation location) {
        if (location.getLocationRole() == LocationRole.REQUESTING_POINT) {
            throw new IllegalArgumentException(
                "'" + location.getVirtualName() + "' is a requesting-point location and cannot issue stock — pick a store location instead");
        }
    }

    private StockIndent requireRequest(Long id) {
        return requestRepository.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("Stock indent not found with id: " + id));
    }

    private StockIndentItem requireLine(StockIndent indent, Long lineId) {
        StockIndentItem line = lineRepository.findById(lineId)
            .orElseThrow(() -> new ResourceNotFoundException("Stock indent line not found with id: " + lineId));
        if (!line.getStockIndent().getId().equals(indent.getId())) {
            throw new ResourceNotFoundException("Stock indent line not found with id: " + lineId);
        }
        return line;
    }

    private void requireStatus(StockIndent indent, StockIndentStatus required, String action) {
        if (indent.getStatus() != required) {
            throw new IllegalArgumentException(
                "Cannot " + action + " a request that is " + indent.getStatus().name().toLowerCase(Locale.ROOT)
                    + " — it must be " + required.name().toLowerCase(Locale.ROOT));
        }
    }

    private StockIndentStatus parseStatus(String value) {
        try {
            return StockIndentStatus.valueOf(value.trim().toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid status '" + value + "'");
        }
    }

    private static String trim(String s) {
        if (s == null) return null;
        String t = s.trim();
        return t.isEmpty() ? null : t;
    }

    private StockIndentResponse toResponse(StockIndent indent) {
        return toResponse(indent, true);
    }

    private StockIndentResponse toResponse(StockIndent indent, boolean includeLines) {
        List<StockIndentItem> lines = lineRepository.findByStockIndentIdOrderByIdAsc(indent.getId());
        long pending = lines.stream().filter(l -> l.getStatus() == StockIndentItemStatus.PENDING).count();
        InventoryLocation requestingLocation = indent.getRequestingLocation();
        InventoryLocation issuingLocation = indent.getIssuingLocation();
        return new StockIndentResponse(
            indent.getId(), requestingLocation.getId(), requestingLocation.getVirtualName(),
            issuingLocation.getId(), issuingLocation.getVirtualName(),
            indent.getStatus().name(), indent.getRequestDate(), indent.getNotes(),
            indent.getCreatedBy(), indent.getCreatedAt(),
            indent.getSubmittedBy(), indent.getSubmittedAt(), indent.getCompletedAt(),
            lines.size(), (int) pending, indent.getIsAutoGenerated(),
            includeLines ? lines.stream().map(this::toLineResponse).toList() : null);
    }

    /**
     * Returns previously-issued stock back to this request's issuing location (Phase 4's
     * "Internal Return" concept) — only meaningful once the line is {@code FULFILLED} (issued;
     * pre-Phase-D this was {@code APPROVED}, since approval and issuing were the same step then).
     * Posts an increasing {@code RETURN} movement (opposite direction from {@code
     * SupplierReturnService}'s own decreasing use of the same transaction type) and accumulates
     * the line's own {@code returnedQty} running total. See the "Internal Return slice"
     * decision-log entry.
     */
    @Transactional
    public StockIndentItemResponse returnLine(Long requestId, Long lineId, StockIndentReturnLineRequest request, String actor) {
        StockIndent indent = requireRequest(requestId);
        StockIndentItem line = requireLine(indent, lineId);
        if (line.getStatus() != StockIndentItemStatus.FULFILLED) {
            throw new IllegalArgumentException("Only a fulfilled (issued) line can be returned");
        }
        BigDecimal openQty = line.getRequestedQty().subtract(line.getReturnedQty());
        if (request.returnedQty().compareTo(openQty) > 0) {
            throw new IllegalArgumentException(
                "Returned quantity (" + request.returnedQty() + ") exceeds what's still returnable on this line (" + openQty + ")");
        }

        Long variantId = line.getVariant() != null ? line.getVariant().getId() : null;
        BigDecimal unitCost = currentUnbatchedUnitCost(line.getProduct().getId(), variantId, indent.getIssuingLocation().getId());

        stockMovementService.recordMovement(new StockMovementRequest(
            line.getProduct().getId(), variantId,
            indent.getIssuingLocation().getId(), null, null,
            "RETURN", "INCREASE", request.returnedQty(), unitCost,
            "Internal Return — Stock Indent #" + indent.getId() + " line #" + line.getId()
                + (request.notes() != null ? " — " + request.notes() : ""), null
        ), actor);

        line.setReturnedQty(line.getReturnedQty().add(request.returnedQty()));
        lineRepository.save(line);
        return toLineResponse(line);
    }

    private StockIndentItemResponse toLineResponse(StockIndentItem line) {
        Product product = line.getProduct();
        ProductVariant variant = line.getVariant();
        StockTransfer sourceTransfer = line.getSourceTransfer();
        PurchaseRequisition raisedRequisition = line.getRaisedRequisition();
        PurchaseRequisitionItem raisedRequisitionItem = line.getRaisedRequisitionItem();
        return new StockIndentItemResponse(
            line.getId(), product.getId(), product.getProductCode(), product.getProductName(),
            variant != null ? variant.getId() : null, variant != null ? variant.getVariantCode() : null, variant != null ? variant.getVariantName() : null,
            product.getBaseUom() != null ? product.getBaseUom().getCode() : null,
            line.getRequestedQty(), line.getStatus().name(),
            line.getResolvedBy(), line.getResolvedAt(), line.getResolutionNotes(),
            line.getReturnedQty(), line.getNotes(),
            line.getStoreDecidedBy(), line.getStoreDecidedAt(), line.getStoreDecisionNotes(),
            sourceTransfer != null ? sourceTransfer.getId() : null,
            raisedRequisition != null ? raisedRequisition.getId() : null,
            raisedRequisitionItem != null ? raisedRequisitionItem.getId() : null);
    }
}
