package com.cms.model.enums;

public enum DocumentType {
    TENTH_MARKSHEET,
    ELEVENTH_MARKSHEET,
    TWELFTH_MARKSHEET,
    TRANSFER_CERTIFICATE,
    COMMUNITY_CERTIFICATE,
    INCOME_CERTIFICATE,
    NATIVITY_CERTIFICATE,
    MIGRATION_CERTIFICATE,
    FIRST_GRADUATE_CERTIFICATE,
    PASSPORT_PHOTO,
    SIGNED_AFFIDAVIT,
    UNDERTAKING_DOCUMENT,
    AADHAR_CARD,
    MEDICAL_FITNESS,
    ELIGIBILITY_CERTIFICATE
}
