package com.cms.inventory.indent.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.cms.inventory.catalog.model.Product;
import com.cms.inventory.catalog.repository.ProductRepository;
import com.cms.inventory.catalog.repository.ProductVariantRepository;
import com.cms.inventory.indent.dto.StockIndentAddLineRequest;
import com.cms.inventory.indent.dto.StockIndentResponse;
import com.cms.inventory.indent.model.IndentOpenQtyProjection;
import com.cms.inventory.indent.repository.StockIndentItemRepository;
import com.cms.inventory.stock.model.ReorderConfigShortageProjection;
import com.cms.inventory.stock.repository.ProductLocationReorderConfigRepository;

@ExtendWith(MockitoExtension.class)
class AutoIndentServiceTest {

    @Mock private ProductLocationReorderConfigRepository configRepository;
    @Mock private StockIndentItemRepository indentItemRepository;
    @Mock private ProductRepository productRepository;
    @Mock private ProductVariantRepository variantRepository;
    @Mock private StockIndentService stockIndentService;
    private AutoIndentService service;

    @BeforeEach
    void setUp() {
        service = new AutoIndentService(configRepository, indentItemRepository, productRepository, variantRepository, stockIndentService);
        lenient().when(indentItemRepository.findOpenQtyByProductAndRequestingLocation()).thenReturn(List.of());
        lenient().when(variantRepository.existsByProductIdAndIsActiveTrue(any())).thenReturn(false);
        lenient().when(stockIndentService.createAutoGenerated(any(), any(), any(), any()))
            .thenReturn(response(1L));
    }

    @Test
    void shouldSkipWhenNoCandidates() {
        when(configRepository.findShortageCandidates()).thenReturn(List.of());
        assertThat(service.generate()).isEqualTo(0);
        verify(stockIndentService, never()).createAutoGenerated(any(), any(), any(), any());
    }

    @Test
    void shouldSkipWhenAlreadyAtOrAboveReorderLevel() {
        when(configRepository.findShortageCandidates()).thenReturn(List.of(
            candidate(10L, 2L, new BigDecimal("10"), new BigDecimal("10"), new BigDecimal("5"), null, 1L)
        ));
        when(productRepository.findAllById(any())).thenReturn(List.of(product(10L)));
        assertThat(service.generate()).isEqualTo(0);
        verify(stockIndentService, never()).createAutoGenerated(any(), any(), any(), any());
    }

    @Test
    void shouldSkipWhenNoDefaultSupplyingLocation() {
        when(configRepository.findShortageCandidates()).thenReturn(List.of(
            candidate(10L, 2L, new BigDecimal("2"), new BigDecimal("10"), new BigDecimal("5"), null, null)
        ));
        when(productRepository.findAllById(any())).thenReturn(List.of(product(10L)));
        assertThat(service.generate()).isEqualTo(0);
        verify(stockIndentService, never()).createAutoGenerated(any(), any(), any(), any());
    }

    @Test
    void shouldSkipProductWithActiveVariants() {
        when(configRepository.findShortageCandidates()).thenReturn(List.of(
            candidate(10L, 2L, new BigDecimal("2"), new BigDecimal("10"), new BigDecimal("5"), null, 1L)
        ));
        when(productRepository.findAllById(any())).thenReturn(List.of(product(10L)));
        when(variantRepository.existsByProductIdAndIsActiveTrue(10L)).thenReturn(true);

        assertThat(service.generate()).isEqualTo(0);
        verify(stockIndentService, never()).createAutoGenerated(any(), any(), any(), any());
    }

    @Test
    void shouldNetAgainstAlreadyOpenIndentQuantity() {
        when(configRepository.findShortageCandidates()).thenReturn(List.of(
            candidate(10L, 2L, new BigDecimal("2"), new BigDecimal("10"), new BigDecimal("5"), null, 1L)
        ));
        when(productRepository.findAllById(any())).thenReturn(List.of(product(10L)));
        // Already 8 units open (2 on hand + 8 open = 10 = reorder level) -> net requirement is 0.
        when(indentItemRepository.findOpenQtyByProductAndRequestingLocation()).thenReturn(List.of(
            openQty(10L, 2L, new BigDecimal("8"))
        ));

        assertThat(service.generate()).isEqualTo(0);
        verify(stockIndentService, never()).createAutoGenerated(any(), any(), any(), any());
    }

    @Test
    void shouldBundleMultipleProductsForSameStorePairIntoOneHeader() {
        when(configRepository.findShortageCandidates()).thenReturn(List.of(
            candidate(10L, 2L, new BigDecimal("2"), new BigDecimal("10"), new BigDecimal("5"), null, 1L),
            candidate(11L, 2L, new BigDecimal("0"), new BigDecimal("8"), new BigDecimal("4"), null, 1L)
        ));
        when(productRepository.findAllById(any())).thenReturn(List.of(product(10L), product(11L)));
        when(stockIndentService.addLine(eq(1L), any())).thenReturn(null);

        int created = service.generate();

        assertThat(created).isEqualTo(2);
        verify(stockIndentService, times(1)).createAutoGenerated(eq(2L), eq(1L), any(LocalDate.class), any());
        verify(stockIndentService, times(2)).addLine(eq(1L), any(StockIndentAddLineRequest.class));
        verify(stockIndentService).submit(1L, "auto-indent");
    }

    @Test
    void shouldCapSuggestedQtyAtMaxStockQty() {
        // reorderLevel 10, onHand 2 -> netRequirement 8; reorderQty 20 -> lotSize 20; maxStock 15 -> cap at 13 (15-2).
        when(configRepository.findShortageCandidates()).thenReturn(List.of(
            candidate(10L, 2L, new BigDecimal("2"), new BigDecimal("10"), new BigDecimal("20"), new BigDecimal("15"), 1L)
        ));
        when(productRepository.findAllById(any())).thenReturn(List.of(product(10L)));
        when(stockIndentService.addLine(eq(1L), any())).thenReturn(null);

        service.generate();

        var captor = org.mockito.ArgumentCaptor.forClass(StockIndentAddLineRequest.class);
        verify(stockIndentService).addLine(eq(1L), captor.capture());
        assertThat(captor.getValue().requestedQty()).isEqualByComparingTo("13");
    }

    // ── fixtures ─────────────────────────────────────────────────────────────

    private Product product(Long id) {
        Product p = new Product();
        p.setId(id);
        p.setProductCode("PROD-" + id);
        p.setProductName("Product " + id);
        p.setIsActive(true);
        return p;
    }

    private ReorderConfigShortageProjection candidate(Long productId, Long locationId, BigDecimal qtyOnHand,
            BigDecimal reorderLevel, BigDecimal reorderQty, BigDecimal maxStockQty, Long defaultSupplyingLocationId) {
        return new ReorderConfigShortageProjection() {
            public Long getConfigId() { return 1L; }
            public Long getProductId() { return productId; }
            public Long getLocationId() { return locationId; }
            public BigDecimal getQtyOnHand() { return qtyOnHand; }
            public BigDecimal getReorderLevel() { return reorderLevel; }
            public BigDecimal getReorderQty() { return reorderQty; }
            public BigDecimal getMaxStockQty() { return maxStockQty; }
            public Long getDefaultSupplyingLocationId() { return defaultSupplyingLocationId; }
        };
    }

    private IndentOpenQtyProjection openQty(Long productId, Long locationId, BigDecimal qty) {
        return new IndentOpenQtyProjection() {
            public Long getProductId() { return productId; }
            public Long getLocationId() { return locationId; }
            public BigDecimal getQty() { return qty; }
        };
    }

    private StockIndentResponse response(Long id) {
        return new StockIndentResponse(id, 2L, "Ward A", 1L, "Main Store", "DRAFT", LocalDate.now(), null,
            "auto-indent", null, null, null, null, 0, 0, true, null);
    }
}
