spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/cms}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    url: ${FLYWAY_DB_URL:${DB_URL:jdbc:postgresql://localhost:5433/cms}}
    user: ${FLYWAY_DB_USERNAME:${DB_USERNAME}}
    password: ${FLYWAY_DB_PASSWORD:${DB_PASSWORD}}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://cms.nursing.sksh.ac.in/realms/cms}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/cms/protocol/openid-connect/certs}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://cms.nursing.sksh.ac.in,https://137.97.6.147,https://172.16.7.209}

keycloak:
  allowed-issuers: ${KEYCLOAK_ALLOWED_ISSUERS:https://cms.nursing.sksh.ac.in/realms/cms,https://137.97.6.147/realms/cms,https://172.16.7.209/realms/cms}
  admin:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:cms}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

cms:
  minio:
    endpoint:   ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket:     ${MINIO_BUCKET:cms-documents}

