spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/cmsdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:cms}
    password: ${DB_PASSWORD:cms}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://dev.raster.in:212/realms/cms}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8280/realms/cms/protocol/openid-connect/certs}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://dev.raster.in:212,https://122.165.219.66:212,https://172.17.1.243:8443}

keycloak:
  allowed-issuers: ${KEYCLOAK_ALLOWED_ISSUERS:https://dev.raster.in:212/realms/cms,https://122.165.219.66:212/realms/cms,https://172.17.1.243:8443/realms/cms}

