spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/cms}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://172.16.7.209/realms/cms}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/cms/protocol/openid-connect/certs}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://172.16.7.209}

