spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cmsdb}
    username: ${DB_USERNAME:cms}
    password: ${DB_PASSWORD:cms}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8280/realms/cms}
