spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8280/realms/cms}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8280/realms/cms/protocol/openid-connect/certs}

keycloak:
  admin:
    password: ${KEYCLOAK_ADMIN_PASSWORD}
